### ISSUE TITLE
After adding clusters it's not obvious what to do next

### ISSUE THREAD

**Issue by stefcameron** [Mirantis/lens-extension-cc#121]
Customer feedback: "After adding clusters it doesn't take me to the clusters - it just leaves me on the Add CCC pane - not entirely sure how to exit it."

Possible solution: Change to a new "summary" screen (provided by the extension) that lists all the clusters that were added so you can click one and activate it.

A new summary screen might remove the need for some of the notifications causing issue #119...?

**Comment by stefcameron** [comment]
Looks like Lens 4.2 will get a new "workspace overview" page, which could help with this, though current designs make it look like it's scoped to a single workspace: https://github.com/lensapp/lens/pull/2047

**Comment by jim-docker** [comment]
What about adding to the Add CCC pane a "Go to to workspace" dropdown that lets you pick a workspace and then navigates to it (either opens its active cluster or, if no active cluster, goes to the the landing page). This is the current behaviour when one switches workspaces. Also note the landing page becomes the workspace overview in https://github.com/lensapp/lens/pull/2047

**Comment by stefcameron** [comment]
> What about adding to the Add CCC pane a "Go to to workspace" dropdown that lets you pick a workspace and then navigates to it (either opens its active cluster or, if no active cluster, goes to the landing page). This is the current behaviour when one switches workspaces. Also note the landing page becomes the workspace overview in [lensapp/lens#2047](https://github.com/lensapp/lens/pull/2047)

Good suggestion, but I'm adding multiple workspaces with multiple clusters, so there's never a "right" workspace or cluster to activate automatically because it'll be "right" only 50% of the time... And I feel like requiring users to choose which workspace to activate after adding via a dropdown is clunky (and the list would keep changing depending on what clusters they select to be added). Plus, if I could produce a nice overview/summary page, I could get rid of some of the notifications I currently post about new workspaces and clusters being created (notifications, at larger scale, aren't going to work well at all).

I think it's great Lens will get a workspace overview page that lists all clusters in it, but I think there will still be a gap with a missing "full overview" page that shows all clusters across all workspaces -- regardless of my extension's needs/desires.

**Comment by stefcameron** [comment]
Depends on https://github.com/Mirantis/lens-extension-cc/issues/249
