### ISSUE TITLE
Update README with new installation instructions and lens install link

### ISSUE THREAD

**Issue by stefcameron** [Mirantis/lens-extension-cc#239]
This Lens issue https://github.com/lensapp/lens/issues/2422 is fixed in https://github.com/lensapp/lens/pull/2394 and adds ability to specify npmjs.com link in install box, as well as use `lens://app/extensions/install/@mirantis/lens-extension-cc?version=2.1.2` (version optional; without it, latest is installed) link to trigger installation.

- [ ] Tracking: https://github.com/lensapp/lens/issues/2688
- [x] Update https://github.com/Mirantis/lens-extension-cc/issues/282 when fix this

**Comment by Nokel81** [comment]
lensapp/lens#2435 is the actual fix PR

**Comment by stefcameron** [comment]
> [lensapp/lens#2435](https://github.com/lensapp/lens/pull/2435) is the actual fix PR

Thank you! 😄

**Comment by stefcameron** [comment]
None of this works right now in Lens 4.2.3, tracking: https://github.com/lensapp/lens/issues/2688

**Comment by stefcameron** [comment]
Note that the actual fix to https://github.com/lensapp/lens/issues/1707 and https://github.com/lensapp/lens/issues/1708 was to support simply entering `@mirantis/lens-extension-cc` (or any other extension name as published to NPM) into the "Install Extension" box and clicking the Install button.

Verified this works on Lens 4.2.4.
