### ISSUE TITLE
Newest release 4.2.3 breaks the extension 

### ISSUE THREAD

**Issue by jpalmer2** [Mirantis/lens-extension-cc#282]
<img width="1446" alt="Screen Shot 2021-04-30 at 11 07 53 AM" src="https://user-images.githubusercontent.com/2455970/116722806-7bb32200-a9a4-11eb-8276-c6b56834f169.png">

**Comment by stefcameron** [comment]
Thanks, @jpalmer2 , I see that. This is a problem with Lens, not this extension, AFAIK. I have reported it to the Lens team.

**Comment by stefcameron** [comment]
Tracking: https://github.com/lensapp/lens/issues/2688

**Comment by stefcameron** [comment]
@jpalmer2 With today's Lens 4.2.4 release, you should be able to install this extension by simply typing `@mirantis/lens-extension-cc` into the "Install Extension" box and clicking on the Install button.
