### ISSUE TITLE
Error When Getting Clusters

### ISSUE THREAD

**Issue by mbentley** [Mirantis/lens-extension-cc#35]
```
Encountered at least one cluster with unexpected or missing metadata. (@mirantis/lens-extension-cc)
```

![screenshot 2020-12-15 at 3 15 15 PM](https://user-images.githubusercontent.com/414445/102267775-60a9af00-3ee8-11eb-97b9-b1b2ad9d241f.png)

In this case, it might have been related to one of the following:

- a cluster that was created but they had only specified 3 managers and no workers yet so it was still in a pending state as a not yet valid configuration
- A cluster that was defined but it had no nodes in the cluster

Those are the only odd things I can find about the container cloud install at the time.  I am almost positive it is the 2nd one - a cluster has been defined but has no nodes in the cluster.

**Comment by mbentley** [comment]
Ah yeah, I just confirmed that it starts happening after I create a cluster without adding any nodes.

**Comment by stefcameron** [comment]
Thanks @mbentley . Are you able to reproduce this again, but this time, press `CMD+OPT+I` while in Lens to open the DevTools and copy/paste any exceptions you see in there here? That would help me to know what part of the cluster spec is missing that my code isn't expecting. Then I could just ignore those clusters, or maybe still support them -- depending on what's missing (i.e. if what's missing isn't required to generate a kubeconfig for it).

**Comment by mbentley** [comment]
[localhost-1608070585843.log](https://github.com/Mirantis/lens-extension-cc/files/5699008/localhost-1608070585843.log)

In this case, we should probably just ignore these clusters (as they don't exist yet).

**Comment by stefcameron** [comment]
Thanks for the log, that helps!

> In this case, we should probably just ignore these clusters (as they don't exist yet).

👍

**Comment by stefcameron** [comment]
This will be fixed in the next release of the extension.
