### ISSUE TITLE
Container Cloud Extension Errors After Closing and Re-Opening Lens

### ISSUE THREAD

**Issue by mbentley** [Mirantis/lens-extension-cc#37]
Lens 4.0.3
Mirantis Container Cloud 2.0.1 extension

Built the extension using:
```
docker run -t --rm -v "${PWD}:/data" -w /data alpine sh -c 'apk add --no-cache npm && npm pack @mirantis/lens-extension-cc'
```

When I install the extension, it is fine but after closing and opening Lens back up, it doesn't show the container cloud extension.  If I disable/enable the extension, it is fine and works again.  Console logs:

[localhost-1608070585843.log](https://github.com/Mirantis/lens-extension-cc/files/5699013/localhost-1608070585843.log)

Looking at the console logs, I was confused because the file definitely existed when I checked and then I was watching the file to see is anything happened when I disabled/enabled the extension but it looks like when Lens starts, it does something with the directories/symlinks as they disappear which is probably why it is happening.  asciinema of it happening while Lens is loading:

[![asciicast](https://asciinema.org/a/wdAf83m6pzlM4QD395uPsJyAo.png)](https://asciinema.org/a/wdAf83m6pzlM4QD395uPsJyAo?t=10)

Let me know if I need to file this against Lens.

**Comment by stefcameron** [comment]
Thanks, Matt. Yes, this is a Lens issue in 4.0.3 discovered earlier today. It will require a Lens issue, if one doesn't already exist. It's not an issue with this extension.
